apiVersion: v1
kind: Service
metadata:
  name: hako-agent
  labels:
    app: hako-agent
spec:
  selector:
    app: hako-agent
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80           # Public-facing port
      targetPort: 8080   # Port your container listens on