name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REPO_NAME: "hako-agent"
  IMAGE_NAME: "hako-agent:latest"
  OCIR_ENDPOINT: "ord.ocir.io"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/kubectl
        kubectl version --client
        
    - name: Configure kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${KUBECONFIG_DATA}" > $HOME/.kube/config

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}
    
    - name: Login to OCIR
      run: echo "${{ secrets.OCI_AUTH_TOKEN }}" | docker login ord.ocir.io -u ${{ secrets.OCI_STORAGE_NAMESPACE}}/${{ secrets.OCI_EMAIL }} --password-stdin

    - name: Tag the Docker image
      run: docker tag ${{ env.IMAGE_NAME }} ord.ocir.io/${{ secrets.OCI_STORAGE_NAMESPACE }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}

    - name: Push the Docker image
      run: docker push ord.ocir.io/${{ secrets.OCI_STORAGE_NAMESPACE }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}

    - name: Deploy new image to OKE
      run: |
        kubectl set image hako-agent \
          ${{ env.IMAGE_NAME }} \
          --namespace hako-agent
  