name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REPO_NAME: "hako-agent"
  IMAGE_NAME: "hako-agent:latest"
  OCIR_ENDPOINT: "ord.ocir.io"
  K8S_NAMESPACE: "hako-agent"
  DEPLOYMENT_NAME: "hako-agent"
  CONTAINER_NAME: "hako-agent"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install kubectl
    run: |
      set -e
      VERSION=$(curl -s https://dl.k8s.io/release/stable.txt)
      if [ -z "$VERSION" ]; then
        echo "Failed to fetch kubectl version from Kubernetes release site"
        exit 1
      fi
      echo "Installing kubectl $VERSION"
      curl -LO "https://dl.k8s.io/release/${VERSION}/bin/linux/amd64/kubectl"
      chmod +x kubectl
      sudo mv kubectl /usr/local/bin/kubectl
      kubectl version --client

    - name: Configure kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > $HOME/.kube/config

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}

    - name: Login to OCIR
      run: echo "${{ secrets.OCI_AUTH_TOKEN }}" | docker login ${{ env.OCIR_ENDPOINT }} -u "${{ secrets.OCI_STORAGE_NAMESPACE }}/${{ secrets.OCI_EMAIL }}" --password-stdin

    - name: Tag the Docker image
      run: docker tag ${{ env.IMAGE_NAME }} ${{ env.OCIR_ENDPOINT }}/${{ secrets.OCI_STORAGE_NAMESPACE }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}

    - name: Push the Docker image
      run: docker push ${{ env.OCIR_ENDPOINT }}/${{ secrets.OCI_STORAGE_NAMESPACE }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}

    - name: Deploy new image to OKE
      run: |
        kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} \
          ${{ env.CONTAINER_NAME }}=${{ env.OCIR_ENDPOINT }}/${{ secrets.OCI_STORAGE_NAMESPACE }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }} \
          --namespace ${{ env.K8S_NAMESPACE }}