name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REPO_NAME: "hako-agent"
  IMAGE_NAME: "hako-agent:latest"
  OCIR_ENDPOINT: "ord.ocir.io"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}
    
    - name: Login to OCIR
      run: echo "${{ secrets.OCI_PASSWORD }}" | docker login ord.ocir.io -u ${{ secrets.OCI_USERNAME }} --password-stdin

    - name: Push the Docker image
      run: docker push ord.ocir.io/${{ secrets.OCI_STORAGE_NAMESPACE }}/${{ secrets.OCI_REPO_NAME }}/${{ secrets.OCI_IMAGE_NAME }}